import { FunFact, Category } from './types';

export const CATEGORIES: Category[] = [
  'Science',
  'History',
  'Animals',
  'Food',
  'Geography',
  'Space',
  'Technology'
];

export const CATEGORY_COLORS: Record<Category, string> = {
  'Science': '#10b981',    // emerald-500
  'Animals': '#f59e0b',    // amber-500
  'History': '#8b5cf6',    // violet-500
  'Food': '#ef4444',       // red-500
  'Geography': '#06b6d4',  // cyan-500
  'Space': '#6366f1',      // indigo-500
  'Technology': '#3b82f6', // blue-500
};

export const INITIAL_FACTS: FunFact[] = [
  // Existing Science, History
  { id: 'f1', fact: "Honey never spoils; edible honey has been found in ancient Egyptian tombs.", category: 'Science' },
  { id: 'f2', fact: "Bananas are naturally radioactive due to their potassium content.", category: 'Science' },
  { id: 'f3', fact: "Water can boil and freeze at the same time, a phenomenon called the triple point.", category: 'Science' },
  { id: 'f7', fact: "There’s enough DNA in your body to stretch from the Sun to Pluto and back 17 times.", category: 'Science' },
  { id: 'f8', fact: "A teaspoon of neutron star material would weigh about 6 billion tons.", category: 'Science' },
  { id: 'f9', fact: "Lightning is hotter than the surface of the Sun.", category: 'Science' },
  { id: 'h1', fact: "The shortest war in history lasted only 38 to 45 minutes between Britain and Zanzibar in 1896.", category: 'History' },
  { id: 'h2', fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.", category: 'History' },
  
  // Animal Facts
  { id: 'a1', fact: "Octopuses have three hearts and blue blood.", category: 'Animals' },
  { id: 'a2', fact: "A group of flamingos is called a flamboyance.", category: 'Animals' },
  { id: 'a3', fact: "Wombats produce cube-shaped poop.", category: 'Animals' },
  { id: 'a4', fact: "Sharks existed before trees.", category: 'Animals' },
  { id: 'a5', fact: "Elephants are the only mammals that cannot jump.", category: 'Animals' },
  { id: 'a6', fact: "A snail can sleep for up to three years.", category: 'Animals' },
  { id: 'a7', fact: "Dolphins have names for each other.", category: 'Animals' },
  { id: 'a8', fact: "Butterflies remember being caterpillars.", category: 'Animals' },
  { id: 'a9', fact: "A shrimp’s heart is in its head.", category: 'Animals' },
  { id: 'a10', fact: "Cows have best friends and get stressed when separated.", category: 'Animals' },
  { id: 'a11', fact: "Octopuses can taste with their suckers.", category: 'Animals' },
  { id: 'a12', fact: "Kangaroos cannot walk backward.", category: 'Animals' },
  { id: 'a13', fact: "An octopus has nine brains.", category: 'Animals' },
  { id: 'a14', fact: "Owls can rotate their heads up to 270 degrees.", category: 'Animals' },
  { id: 'a15', fact: "Sea otters hold hands while sleeping to avoid drifting apart.", category: 'Animals' },
  { id: 'a16', fact: "Tigers have striped skin, not just striped fur.", category: 'Animals' },
  { id: 'a17', fact: "A group of crows is called a murder.", category: 'Animals' },
  { id: 'a18', fact: "Sloths can hold their breath longer than dolphins.", category: 'Animals' },
  { id: 'a19', fact: "Some frogs can freeze solid and survive.", category: 'Animals' },
  { id: 'a20', fact: "Parrots can live over 60 years.", category: 'Animals' },

  // Space Facts
  { id: 's1', fact: "Space is completely silent because sound needs a medium to travel.", category: 'Space' },
  { id: 's2', fact: "The Sun makes up about 99.86% of the mass of the solar system.", category: 'Space' },
  { id: 's3', fact: "One million Earths could fit inside the Sun.", category: 'Space' },
  { id: 's4', fact: "A day on Venus is longer than a year on Venus.", category: 'Space' },
  { id: 's5', fact: "Neutron stars are so dense that a teaspoon would weigh billions of tons.", category: 'Space' },
  { id: 's6', fact: "There are more stars in the universe than grains of sand on Earth.", category: 'Space' },

  // Geography Facts
  { id: 'g1', fact: "Africa is the only continent located in all four hemispheres.", category: 'Geography' },
  { id: 'g2', fact: "Russia is the largest country in the world by land area.", category: 'Geography' },
  { id: 'g3', fact: "Vatican City is the smallest country in the world.", category: 'Geography' },
  { id: 'g4', fact: "Mount Everest is the highest mountain above sea level.", category: 'Geography' },
  { id: 'g5', fact: "The Dead Sea is one of the saltiest bodies of water on Earth.", category: 'Geography' },
  { id: 'g6', fact: "Antarctica is the coldest, driest, and windiest continent.", category: 'Geography' },
  { id: 'g7', fact: "The Nile River is often considered the longest river in the world.", category: 'Geography' },
  { id: 'g8', fact: "Asia is the largest and most populated continent.", category: 'Geography' },
  { id: 'g9', fact: "Australia is both a country and a continent.", category: 'Geography' },
  { id: 'g10', fact: "The Amazon Rainforest spans over nine countries.", category: 'Geography' },
  { id: 'g11', fact: "Greenland is the largest island in the world.", category: 'Geography' },
  { id: 'g12', fact: "The Sahara is the largest hot desert on Earth.", category: 'Geography' },
  { id: 'g13', fact: "The Pacific Ocean is the largest ocean on Earth.", category: 'Geography' },
  { id: 'g14', fact: "The Mariana Trench is the deepest part of the ocean.", category: 'Geography' },
  { id: 'g15', fact: "Japan is made up of over 6,800 islands.", category: 'Geography' },
  { id: 'g16', fact: "Iceland has more volcanoes than any other country.", category: 'Geography' },
  { id: 'g17', fact: "Nigeria is the most populous country in Africa.", category: 'Geography' },
  { id: 'g18', fact: "Brazil contains most of the Amazon River.", category: 'Geography' },
  { id: 'g19', fact: "Europe is the second smallest continent.", category: 'Geography' },
  { id: 'g20', fact: "The equator divides Earth into the Northern and Southern Hemispheres.", category: 'Geography' },
  { id: 'g21', fact: "Mount Kilimanjaro is the tallest mountain in Africa.", category: 'Geography' },
  { id: 'g22', fact: "Canada has more lakes than the rest of the world combined.", category: 'Geography' },
  { id: 'g23', fact: "The longest mountain range on Earth is underwater.", category: 'Geography' },
  { id: 'g24', fact: "China and Russia share the longest international border.", category: 'Geography' },
  { id: 'g25', fact: "The Great Barrier Reef is the largest living structure on Earth.", category: 'Geography' },
  { id: 'g26', fact: "Sudan has more pyramids than Egypt.", category: 'Geography' },
  { id: 'g27', fact: "Indonesia has the most active volcanoes in the world.", category: 'Geography' },
  { id: 'g28', fact: "The Mediterranean Sea touches three continents.", category: 'Geography' },
  { id: 'g29', fact: "Venice is built on over 100 small islands.", category: 'Geography' },
  { id: 'g30', fact: "Alaska is the largest U.S. state.", category: 'Geography' },
  { id: 'g31', fact: "The Amazon River releases more water than any other river.", category: 'Geography' },
  { id: 'g32', fact: "The Himalayas are still growing each year.", category: 'Geography' },
  { id: 'g33', fact: "France has the most time zones of any country.", category: 'Geography' },
  { id: 'g34', fact: "Lake Baikal is the deepest freshwater lake in the world.", category: 'Geography' },
  { id: 'g35', fact: "Africa has no major mountain ranges like other continents.", category: 'Geography' },
  { id: 'g36', fact: "The Netherlands has land below sea level.", category: 'Geography' },
  { id: 'g37', fact: "Chile is one of the longest north-south countries.", category: 'Geography' },
  { id: 'g38', fact: "The Arctic Ocean is the smallest ocean.", category: 'Geography' },
  { id: 'g39', fact: "The equator passes through 13 countries.", category: 'Geography' },
  { id: 'g40', fact: "The Andes is the longest continental mountain range.", category: 'Geography' },
  { id: 'g41', fact: "The Mississippi River flows through 10 U.S. states.", category: 'Geography' },
  { id: 'g42', fact: "Monaco is smaller than New York’s Central Park.", category: 'Geography' },
  { id: 'g43', fact: "Africa is drifting apart due to tectonic movement.", category: 'Geography' },
  { id: 'g44', fact: "The driest place on Earth is the Atacama Desert.", category: 'Geography' },
  { id: 'g45', fact: "There are seven continents on Earth.", category: 'Geography' },
  { id: 'g46', fact: "The longest river in Asia is the Yangtze River.", category: 'Geography' },
  { id: 'g47', fact: "Papua New Guinea has over 800 languages.", category: 'Geography' },
  { id: 'g48', fact: "The equator is about 40,075 km long.", category: 'Geography' },
  { id: 'g49', fact: "The Red Sea is actually blue.", category: 'Geography' },
  { id: 'g50', fact: "The North Pole has no land beneath it.", category: 'Geography' },
  { id: 'g51', fact: "Africa is larger than the U.S., China, India, and Europe combined.", category: 'Geography' },
  { id: 'g52', fact: "The Caspian Sea is the largest inland body of water.", category: 'Geography' },
  { id: 'g53', fact: "The longest river in Europe is the Volga.", category: 'Geography' },
  { id: 'g54', fact: "Mount Fuji is a dormant volcano.", category: 'Geography' },
  { id: 'g55', fact: "The Amazon Rainforest produces a large portion of Earth’s oxygen.", category: 'Geography' },
  { id: 'g56', fact: "Some islands are actually volcano tops.", category: 'Geography' },
  { id: 'g57', fact: "The Ring of Fire surrounds the Pacific Ocean.", category: 'Geography' },
  { id: 'g58', fact: "There are more than 195 countries in the world.", category: 'Geography' },
  { id: 'g59', fact: "The Gobi Desert spans two countries.", category: 'Geography' },
  { id: 'g60', fact: "Earth is slightly flattened at the poles.", category: 'Geography' },
  { id: 'g61', fact: "The longest coastline belongs to Canada.", category: 'Geography' },
  { id: 'g62', fact: "Africa has the fastest-growing population.", category: 'Geography' },
  { id: 'g63', fact: "The Tropic of Cancer passes through Mexico.", category: 'Geography' },
  { id: 'g64', fact: "The Nile flows northward.", category: 'Geography' },
  { id: 'g65', fact: "South America has the world’s largest waterfall system.", category: 'Geography' },
  { id: 'g66', fact: "The Indian Ocean is the warmest ocean.", category: 'Geography' },
  { id: 'g67', fact: "Europe has no deserts.", category: 'Geography' },
  { id: 'g68', fact: "Antarctica has no permanent residents.", category: 'Geography' },
  { id: 'g69', fact: "The world’s largest plateau is in Tibet.", category: 'Geography' },
  { id: 'g70', fact: "Earth has over 7,000 islands.", category: 'Geography' },
  { id: 'g71', fact: "The Alps stretch across eight countries.", category: 'Geography' },
  { id: 'g72', fact: "The equator has equal day and night lengths.", category: 'Geography' },
  { id: 'g73', fact: "Some countries exist entirely within another country.", category: 'Geography' },
  { id: 'g74', fact: "The longest canal is the Grand Canal in China.", category: 'Geography' },
  { id: 'g75', fact: "Africa has the world’s longest river and largest desert.", category: 'Geography' },

  // Technology Facts
  { id: 't1', fact: "The first computer mouse was made of wood.", category: 'Technology' },
  { id: 't2', fact: "The first computer weighed more than 27 tons.", category: 'Technology' },
  { id: 't3', fact: "Email existed before the World Wide Web.", category: 'Technology' },
  { id: 't4', fact: "The first website is still online today.", category: 'Technology' },
  { id: 't5', fact: "More computing power exists in a smartphone than in NASA’s computers during the Moon landing.", category: 'Technology' },
  { id: 't6', fact: "The first mobile phone call was made in 1973.", category: 'Technology' },
  { id: 't7', fact: "The QWERTY keyboard layout was designed to slow typists down.", category: 'Technology' },
  { id: 't8', fact: "The first webcam was used to watch a coffee pot.", category: 'Technology' },
  { id: 't9', fact: "Over 90% of the world’s data was created in the last few years.", category: 'Technology' },
  { id: 't10', fact: "The first video game was created in the 1950s.", category: 'Technology' },
  { id: 't11', fact: "Bluetooth is named after a Viking king.", category: 'Technology' },
  { id: 't12', fact: "The original name for Google was Backrub.", category: 'Technology' },
  { id: 't13', fact: "The first hard drive could store only 5 MB of data.", category: 'Technology' },
  { id: 't14', fact: "The Internet was originally created for military communication.", category: 'Technology' },
  { id: 't15', fact: "The first iPhone had no copy-and-paste feature.", category: 'Technology' },
  { id: 't16', fact: "Touchscreens were invented before personal computers.", category: 'Technology' },
  { id: 't17', fact: "The first digital camera was invented in 1975.", category: 'Technology' },
  { id: 't18', fact: "More people have mobile phones than toilets.", category: 'Technology' },
  { id: 't19', fact: "The password '123456' is still one of the most common.", category: 'Technology' },
  { id: 't20', fact: "CAPTCHA stands for Completely Automated Public Turing test.", category: 'Technology' },
  { id: 't21', fact: "The first domain name ever registered was symbolics.com.", category: 'Technology' },
  { id: 't22', fact: "Wi-Fi does not stand for anything; it’s a brand name.", category: 'Technology' },
  { id: 't23', fact: "The first computer virus appeared in the 1980s.", category: 'Technology' },
  { id: 't24', fact: "NASA still uses some floppy disks.", category: 'Technology' },
  { id: 't25', fact: "The first text message said 'Merry Christmas.'", category: 'Technology' },
  { id: 't26', fact: "Computers can generate random numbers faster than humans.", category: 'Technology' },
  { id: 't27', fact: "The original PlayStation was meant to work with Nintendo.", category: 'Technology' },
  { id: 't28', fact: "Artificial intelligence dates back to the 1950s.", category: 'Technology' },
  { id: 't29', fact: "More than 500 hours of video are uploaded to YouTube every minute.", category: 'Technology' },
  { id: 't30', fact: "The first programming language was created in the 1940s.", category: 'Technology' },
  { id: 't31', fact: "Spam emails are named after canned meat.", category: 'Technology' },
  { id: 't32', fact: "The first laptop weighed over 11 kilograms.", category: 'Technology' },
  { id: 't33', fact: "The first smartwatch was made in the 1980s.", category: 'Technology' },
  { id: 't34', fact: "Google processes billions of searches every day.", category: 'Technology' },
  { id: 't35', fact: "The '@' symbol was chosen for email in 1971.", category: 'Technology' },
  { id: 't36', fact: "The first emoji was created in Japan.", category: 'Technology' },
  { id: 't37', fact: "Data stored on CDs can degrade over time.", category: 'Technology' },
  { id: 't38', fact: "The first 1GB hard drive cost about $40,000.", category: 'Technology' },
  // Fix: Renamed property from 'base64' to 'fact' to comply with the FunFact interface
  { id: 't39', fact: "Most ATM machines still run on Windows.", category: 'Technology' },
  { id: 't40', fact: "The first computer programmer was Ada Lovelace.", category: 'Technology' },
  { id: 't41', fact: "QR codes were invented in 1994.", category: 'Technology' },
  { id: 't42', fact: "The Internet weighs about as much as a strawberry.", category: 'Technology' },
  { id: 't43', fact: "The first phone with a camera appeared in 2000.", category: 'Technology' },
  { id: 't44', fact: "Silicon Valley is named after silicon used in chips.", category: 'Technology' },
  { id: 't45', fact: "The first mechanical calculator was built in the 1600s.", category: 'Technology' },
  { id: 't46', fact: "Robots can perform surgery with extreme precision.", category: 'Technology' },
  { id: 't47', fact: "The first computer password was used in 1961.", category: 'Technology' },
  { id: 't48', fact: "Hard drives store data magnetically.", category: 'Technology' },
  { id: 't49', fact: "The first touchscreen phone appeared before smartphones.", category: 'Technology' },
  { id: 't50', fact: "AI can now generate art, music, and text.", category: 'Technology' },
  { id: 't51', fact: "The first USB flash drive appeared in 2000.", category: 'Technology' },
  { id: 't52', fact: "Voice assistants use machine learning.", category: 'Technology' },
  { id: 't53', fact: "Most internet traffic is generated by bots.", category: 'Technology' },
  { id: 't54', fact: "The first video uploaded to YouTube was in 2005.", category: 'Technology' },
  { id: 't55', fact: "A single Google search uses less energy than boiling water.", category: 'Technology' },
  { id: 't56', fact: "The first electric computer was built in 1945.", category: 'Technology' },
  { id: 't57', fact: "Modern cars contain millions of lines of code.", category: 'Technology' },
  { id: 't58', fact: "Cloud computing still relies on physical servers.", category: 'Technology' },
  { id: 't59', fact: "The first smartwatch could only store phone numbers.", category: 'Technology' },
  { id: 't60', fact: "The first computer bug was an actual moth.", category: 'Technology' },
  { id: 't61', fact: "AI systems improve by learning from data.", category: 'Technology' },
  { id: 't62', fact: "The first calculator could only add and subtract.", category: 'Technology' },
  { id: 't63', fact: "Passwords were introduced to protect shared computers.", category: 'Technology' },
  { id: 't64', fact: "Smartphones contain rare earth metals.", category: 'Technology' },
  { id: 't65', fact: "The first MP3 was created in the 1990s.", category: 'Technology' },
  { id: 't66', fact: "Technology allows real-time global communication.", category: 'Technology' },
  { id: 't67', fact: "Self-driving cars rely on sensors and AI.", category: 'Technology' },
  { id: 't68', fact: "The first internet message was sent in 1969.", category: 'Technology' },
  { id: 't69', fact: "Most modern watches are more powerful than early computers.", category: 'Technology' },
  { id: 't70', fact: "AI can recognize faces better than humans in some cases.", category: 'Technology' },
  { id: 't71', fact: "The first electric keyboard appeared in the 1800s.", category: 'Technology' },
  { id: 't72', fact: "Technology evolves faster than any other human invention.", category: 'Technology' },
  { id: 't73', fact: "The average person checks their phone over 100 times a day.", category: 'Technology' },
  { id: 't74', fact: "The first online purchase was a pizza.", category: 'Technology' },
  { id: 't75', fact: "Modern chips have billions of transistors.", category: 'Technology' },
  { id: 't76', fact: "Technology enables remote work worldwide.", category: 'Technology' },
  { id: 't77', fact: "Early computers had no screens.", category: 'Technology' },
  { id: 't78', fact: "The first robot was created in the 1950s.", category: 'Technology' },
  { id: 't79', fact: "Technology has transformed nearly every industry.", category: 'Technology' }
];
